http:
  routers:
    backend-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: backend-service

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:8080"